version: "2"
services:
  web:
    build: .
    ports:
      - "5001:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
  client-side-test:
    image: nginx:alpine
    ports:
      - "5002:80"
    volumes:
      - ./client-side:/usr/share/nginx/html
    depends_on:
      - web
volumes:
  data-volume: